# Case 2: Cargo Ship
The ship MS Leiden is traveling on a route involving five harbors in north-
ern Europe: Rotterdam, Hamburg, Kiel, Aarhus, and Copenhagen. You have
been asked to help the Captain with the loading and unloading plan (for the
destination harbors) that produces

- even and well-balanced solution
- a solution that is easy to unload (so that containers that are earlier un-loaded are not beneath containers that are later unloaded)
- solutions that can integrate as many containers as possible

The following details about the problem are provided:
1. The ship is now docked in Rotterdam. After visiting Rotterdam, the ship
will be traveling to Hamburg, Aarhus, and Copenhagen, in that order. The
containers destined for Rotterdam have been unloaded and the containers
destined for the remaining three harbors have to be loaded on the ship.
2. MS Leiden is a rather small container ship. It has eight bays, three tiers
and four rows. The layout of the ship is shown in the figure below.
3. Containers should be loaded such that a container that has to be unloaded
earlier should be placed in a higher position.
4. Each cell in the above figure is able to hold a forty-foot container. That
is, the ship has room for 8 × 3 × 4 = 96 forty-foot containers.
5. A forty-foot container can be placed on-top of another forty-foot container,
but not on top of an empty cell. We assume that only forty-foot containers
are loaded on the ship. Each container has a destination port.
6. Each container $i$ has a certain weight $w_i$. If a container is much heavier
than another $i$ container $j$, say $w_i − w_j > δ_w$, then it is not allowed to
place $w_i$ on top of $w_j$ .
7. The containers should be balanced in a way that is evenly distributed. The
longitudinal center of gravity should be as close as possible to the middle
of the container section of the ship. Secondly, the latitudinal center of
gravity should be as much to the middle as possible. Note that the center
of gravity can be computed as the weighted sum of the centroids of the
containers, where the weights are the total weight of the containers.

![title](cargo3.png)

In [3]:
from desdeo_problem import variable_builder, ScalarObjective, ScalarConstraint, MOProblem
from desdeo_problem.testproblems.TestProblems import test_problem_builder
from desdeo_emo.population import Population

from desdeo_emo.EAs import NSGAIII, PPGA
from desdeo_mcdm.interactive.NIMBUS import NIMBUS

import numpy as np

# desdeo.probdefs.Problem.__abstractmethods__ = set()
# desdeo docs: https://desdeo.readthedocs.io/en/latest/

## Code

Balance score can be calculated as:
The containers should be balanced in a way that is evenly distributed. The
longitudinal center of gravity should be as close as possible to the middle
of the container section of the ship. Secondly, the latitudinal center of
gravity should be as much to the middle as possible. Note that the center
of gravity can be computed as the weighted sum of the centroids of the
containers, where the weights are the total weight of the containers.

In [4]:
# Create DATA
# n = np.random.randint(10, 96)
n = 50
h = np.random.randint(1, 4, n)
w = np.random.randint(2000, 40000, n)
DATA = np.array(list(zip(h,w)))

HARBORS = np.unique(DATA[:,0])

### Helper functions

In [14]:
def remove_harbor_containers(configuration, destination):
    # Example of removing container 1 from a single stack: 
    # [2,1,2] -> remove number -> [2,2] -> add to length of 3 -> [2,2,0]
    for bay in range(configuration.shape[0]):
        for row in range(configuration.shape[2]):
            stack = configuration[bay, :, row, :]
            if destination in stack[:,0]:
                stack = stack[stack[:,0] != destination]
                stack = np.append(stack, np.zeros((3-len(stack),2)), axis=0)
                configuration[bay, :, row, :] = stack
    return configuration

def positions_to_matrix(positions):
    global temp_pos
    temp_pos = positions.copy()
    configuration = np.zeros((8,3,4,2), dtype=int)

    for i, position in enumerate(positions):

        layer = int(position // 32)
        position = position % 32
        bay = int(position // 4)
        row = int(position % 4)
        
        configuration[bay, layer, row, :] = DATA[i]

    return configuration

def create_population(pop_size):

    sorted_data = np.flip(DATA[:, 1].argsort(), axis=0)

    population = []
    for _ in range(pop_size):

        individual = np.zeros(len(DATA))
        for idx in sorted_data:

            while True:

                rand_position = np.random.randint(1, 33)

                positions = set(np.arange(rand_position, 97, 32)) - set(individual)

                if len(positions) > 0: 
                    individual[idx] = min(positions)
                    break
        
        population.append(individual-1)

    return np.array(population)

### Objective 1: Stability

In [21]:
def sum_tiers(configuration):

    only_weights = configuration[:, :, :, 1]
    summed_configuration = np.sum(only_weights, axis=1)

    return summed_configuration

def get_longitudinal_center(summed_configuration):

    weights = np.sum(summed_configuration, axis=1)
    positions = np.arange(1, 9)

    sum_weights = np.sum(weights)
    if sum_weights != 0:
        return np.sum(weights * positions) / sum_weights
    else:
        return 1

def get_lattitudinal_center(summed_configuration):

    weights = np.sum(summed_configuration, axis=0)
    positions = np.arange(1, 5)

    sum_weights = np.sum(weights)
    if sum_weights != 0:
        return np.sum(weights * positions) / sum_weights
    else:
        return 1


def calculate_centers(configuration):

    summed_configuration = sum_tiers(configuration)

    longitudinal_center = get_longitudinal_center(summed_configuration)
    lattitudinal_center = get_lattitudinal_center(summed_configuration)

    return longitudinal_center, lattitudinal_center

def get_score(configuration):

    longitudinal_center, lattitudinal_center = calculate_centers(configuration)

    long_error, latt_error = abs(longitudinal_center - 4.5), abs(lattitudinal_center - 2.5)

    return long_error + latt_error

def calculate_total_stability(candidate_solutions):

    stability_scores = []

    for candidate in candidate_solutions:

        configuration = positions_to_matrix(candidate)

        stability_score = 0
        for i in HARBORS:
            stability_score += get_score(configuration)
            
            if i < 3:
                configuration = remove_harbor_containers(configuration, i)
        
        stability_scores.append(stability_score)
    # print('Stability scores:',stability_scores)
    return stability_scores

In [22]:
configuration = positions_to_matrix([34.62940047, 70.55500473, 17.87867337, 71.48437768, 71.53891922, 17.35121299, 40.18080825, 27.60435269, 27.15240865, 20.19477824])

stability_score = 0

stability_score += get_score(configuration)
    
configuration2 = remove_harbor_containers(configuration, 1)

summed_configuration = sum_tiers(configuration2)
print(summed_configuration)
# longitudinal_center, lattitudinal_center = calculate_centers(configuration2)

[[    0     0 16029     0]
 [    0     0 29837 25291]
 [17375     0     0     0]
 [    0     0     0     0]
 [    0  2985     0     0]
 [12384     0     0     0]
 [    0     0     0  7963]
 [    0     0     0     0]]


### Objective 2: Unloading time

In [23]:
def get_unloading_time(candidate_solutions):

    unloading_times = []
    
    for candidate in candidate_solutions:

        configuration = positions_to_matrix(candidate)
        only_harbors = configuration[:, :, :, 0]

        unloading_time = 0
        for i in range(8):
            for j in range(4):
                stack = only_harbors[i, :, j]
                stack = stack[stack != 0]
                if len(stack) > 1:
                    if tuple(stack) == (2,1,3):
                        return 4
                    for layer in range(len(stack)-1):
                        if stack[layer] == 1:
                            if stack[layer+1] != 1:
                                unloading_time += 2
                            if len(stack[layer:]) > 2:
                                if stack[layer+2] != 1 and stack[layer+1] != 1:
                                    unloading_time += 2
                        elif stack[layer] == 2:
                            if stack[layer+1] == 3:
                                unloading_time += 2
                            if len(stack[layer:]) > 2:
                                if stack[layer+2] == 3 and stack[layer+1] == 3:
                                    unloading_time += 2
        unloading_times.append(unloading_time/n)
    # print('Unloading times:',unloading_times)
    return unloading_times

In [24]:
def func(stack):
    unloading_time = 0
    if tuple(stack) == (2,1,3):
        return 4
    for layer in range(len(stack)-1):
        if stack[layer] == 1:
            if stack[layer+1] != 1:
                unloading_time += 2
            if len(stack[layer:]) > 2:
                if stack[layer+2] != 1 and stack[layer+1] != 1:
                    unloading_time += 2
        elif stack[layer] == 2:
            if stack[layer+1] == 3:
                unloading_time += 2
            if len(stack[layer:]) > 2:
                if stack[layer+2] == 3 and stack[layer+1] == 3:
                    unloading_time += 2
    return unloading_time

In [25]:
func([2, 1, 3])

4

In [27]:
# Constants
delta_weight = 2000

# Constraints
# 1. Containers can't be placed on the same position
# 2. Containers can not levitate
# 3. Containers can only weigh delta_weight kg more than the container below it
# 
# Objectives
# 1. Minimize the long_error + latt_error (maximize the stability of the ship)
# 2. Minimize the unloading time of the ship

# Create variables
var_names = ["c"+str(id) for id in range(len(DATA))]

initial_values = [pos for pos in range(len(DATA))]
lower_bounds = [0] * len(DATA)
upper_bounds = [95.9999] * len(DATA)

variables = variable_builder(var_names, initial_values, lower_bounds, upper_bounds)

# Create objectives
objectives = [
    ScalarObjective(name="Stability", evaluator=calculate_total_stability, maximize=False),
    ScalarObjective(name="Unloading time", evaluator=get_unloading_time, maximize=False)
    ]

# Create constraints
def overlapping_eval(candidates, fitnesses):

    constraint_values = []
    for positions in candidates:
        positions = [int(pos) for pos in positions]
        
        if n != len(set(positions)):
            constraint_values.append(-1)
        else:
            constraint_values.append(1)

    return constraint_values
    

def overlapping_eval2(candidates, fitnesses):

    constraint_values = []
    for positions in candidates:
        positions = [int(pos) for pos in positions]
        
        if n != len(set(positions)):
            constraint_values.append(-1 * (n - len(set(positions))))
        else:
            constraint_values.append(1)

    return constraint_values


def levitating_eval(candidates, fitnesses):

    constraint_values = []
    for positions in candidates:

        positions = [int(pos) for pos in positions]
        
        breach = False

        for pos in positions:

            if pos < 32:
                continue
            else:
                # pos_below = np.arange(pos-32, -1, -32)
                pos_below = pos - 32
                if not pos_below in positions:
                    breach = True
                    break
        
        if breach:
            constraint_values.append(-1)
        else:
            constraint_values.append(1)
            
    return constraint_values


def levitating_eval2(candidates, fitnesses):

    constraint_values = []
    for positions in candidates:

        positions = [int(pos) for pos in positions]
        
        breachness = 0

        for pos in positions:

            if pos < 32:
                continue
            else:
                # pos_below = np.arange(pos-32, -1, -32)
                pos_below = pos - 32
                if not pos_below in positions:
                    # print('We have:',pos,' but we dont have:', pos_below)
                    breachness -= 1
        
        if breachness < 0:
            constraint_values.append(breachness)
        else:
            constraint_values.append(1)
            
    return constraint_values


def weight_eval(candidates, fitnesses):

    constraint_values = []
    for positions in candidates:

        positions = [int(pos) for pos in positions]

        pos_weights = list(zip(positions, DATA[:,1]))

        breach = False

        for pos, weight in pos_weights:
            if pos < 32:
                continue
            else:
                pos_below = pos - 32
                try:
                    weight_below = pos_weights[positions.index(pos_below)][1]
                    if weight > weight_below + delta_weight:
                        breach = True
                        break
                except:
                    continue
        if breach:
            constraint_values.append(-1)
        else:
            constraint_values.append(1)

    return constraint_values


def weight_eval2(candidates, fitnesses):

    constraint_values = []
    for positions in candidates:

        positions = [int(pos) for pos in positions]

        pos_weights = list(zip(positions, DATA[:,1]))
        breachness = 0
        for pos, weight in pos_weights:
            if pos < 32:
                continue
            else:
                pos_below = pos - 32
                try:
                    weight_below = pos_weights[positions.index(pos_below)][1]
                    if weight > weight_below + delta_weight:
                        breachness += weight_below + delta_weight - weight
                except:
                    continue
        if breachness < 0:
            constraint_values.append(breachness)            
        else:
            constraint_values.append(1)
    return constraint_values


constraints = [
    ScalarConstraint(name="Overlapping", n_decision_vars=len(DATA), n_objective_funs=2, evaluator=overlapping_eval2),
    ScalarConstraint(name="Levitating", n_decision_vars=len(DATA), n_objective_funs=2, evaluator=levitating_eval2),
    ScalarConstraint(name="Weight", n_decision_vars=len(DATA), n_objective_funs=2, evaluator=weight_eval2)
    ]

problem = MOProblem(objectives, variables, constraints)

method = 'EA'

if method == 'EA':
    
    pop_size = 99
    new_population = create_population(pop_size)
    initial_population = Population(
        problem=problem,
        pop_size=1
        ).add(
            offsprings=new_population
        )

    # Evolutionary Algorithm
    # Create an algorithm
    evolver = NSGAIII(problem=problem,
        n_iterations=10,
        n_gen_per_iter=20,
        population_size=pop_size+1,
        # initial_population=initial_population
        )

    # Run the algorithm
    iter = 0
    while evolver.continue_evolution():
        print('Generation:',iter)
        print('Average stability:',np.average(evolver.population.fitness[:,0]))
        print('Average unloading time:',np.average(evolver.population.fitness[:,1]),'\n')
        evolver.iterate()
        iter += 1

elif method == 'NIMBUS':

    method = NIMBUS(problem, "scipy_de")

    classification_request, plot_request = method.start()


Generation: 0
Average stability: 1.5954838457694926
Average unloading time: 4.0 



C:\Users\lcdew\AppData\Roaming\Python\Python38\site-packages\desdeo_emo\selection\NSGAIII_select.py:165: RuntimeWarning:

divide by zero encountered in divide



Generation: 1
Average stability: 0.44298171601022945
Average unloading time: 4.0 



C:\Users\lcdew\AppData\Roaming\Python\Python38\site-packages\desdeo_emo\selection\NSGAIII_select.py:165: RuntimeWarning:

divide by zero encountered in divide



Generation: 2
Average stability: 0.3797317920591016
Average unloading time: 4.0 



C:\Users\lcdew\AppData\Roaming\Python\Python38\site-packages\desdeo_emo\selection\NSGAIII_select.py:165: RuntimeWarning:

divide by zero encountered in divide



Generation: 3
Average stability: 0.34936834686013013
Average unloading time: 4.0 



C:\Users\lcdew\AppData\Roaming\Python\Python38\site-packages\desdeo_emo\selection\NSGAIII_select.py:165: RuntimeWarning:

divide by zero encountered in divide



Generation: 4
Average stability: 0.32742959021358575
Average unloading time: 4.0 



C:\Users\lcdew\AppData\Roaming\Python\Python38\site-packages\desdeo_emo\selection\NSGAIII_select.py:165: RuntimeWarning:

divide by zero encountered in divide



Generation: 5
Average stability: 0.3115166461642476
Average unloading time: 4.0 



C:\Users\lcdew\AppData\Roaming\Python\Python38\site-packages\desdeo_emo\selection\NSGAIII_select.py:165: RuntimeWarning:

divide by zero encountered in divide



Generation: 6
Average stability: 0.2960589139367891
Average unloading time: 4.0 



C:\Users\lcdew\AppData\Roaming\Python\Python38\site-packages\desdeo_emo\selection\NSGAIII_select.py:165: RuntimeWarning:

divide by zero encountered in divide



Generation: 7
Average stability: 0.2856326554647063
Average unloading time: 4.0 



C:\Users\lcdew\AppData\Roaming\Python\Python38\site-packages\desdeo_emo\selection\NSGAIII_select.py:165: RuntimeWarning:

divide by zero encountered in divide



Generation: 8
Average stability: 0.27372253481501263
Average unloading time: 4.0 



C:\Users\lcdew\AppData\Roaming\Python\Python38\site-packages\desdeo_emo\selection\NSGAIII_select.py:165: RuntimeWarning:

divide by zero encountered in divide



Generation: 9
Average stability: 0.2665497283657878
Average unloading time: 4.0 



C:\Users\lcdew\AppData\Roaming\Python\Python38\site-packages\desdeo_emo\selection\NSGAIII_select.py:165: RuntimeWarning:

divide by zero encountered in divide



In [28]:
pop_size = 100
initial_population = create_population(pop_size)

print(overlapping_eval2(initial_population,[]))
print(levitating_eval2(initial_population,[]))
print(weight_eval2(initial_population,[]))

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [29]:
if method == 'EA':
    print(evolver.population.constraint)
    print(evolver.population.fitness)
elif method == 'NIMBUS':
    print(classification_request.content["objective_values"])

[[-1.00000e+01 -1.50000e+01 -7.92700e+04]
 [-9.00000e+00 -1.60000e+01 -1.08751e+05]
 [-1.30000e+01 -2.30000e+01 -5.25230e+04]
 [-1.10000e+01 -1.80000e+01 -2.55850e+04]
 [-1.10000e+01 -1.70000e+01 -4.31050e+04]
 [-1.00000e+01 -1.00000e+01 -1.03013e+05]
 [-1.20000e+01 -1.50000e+01 -7.00400e+04]
 [-1.00000e+01 -1.80000e+01 -8.43840e+04]
 [-1.50000e+01 -2.10000e+01 -3.47460e+04]
 [-9.00000e+00 -1.60000e+01 -1.07705e+05]
 [-1.20000e+01 -1.50000e+01 -8.87590e+04]
 [-8.00000e+00 -1.60000e+01 -5.33770e+04]
 [-1.00000e+01 -1.40000e+01 -2.97390e+04]
 [-8.00000e+00 -1.80000e+01 -4.29490e+04]
 [-9.00000e+00 -9.00000e+00 -9.87810e+04]
 [-1.10000e+01 -2.10000e+01 -2.35890e+04]
 [-1.20000e+01 -2.00000e+01 -7.38450e+04]
 [-1.10000e+01 -2.00000e+01 -4.09730e+04]
 [-8.00000e+00 -1.60000e+01 -4.77200e+04]
 [-8.00000e+00 -1.20000e+01 -1.13909e+05]
 [-7.00000e+00 -1.40000e+01 -8.08170e+04]
 [-1.00000e+01 -1.90000e+01 -8.94890e+04]
 [-1.00000e+01 -1.50000e+01 -2.77560e+04]
 [-1.10000e+01 -2.20000e+01 -7.229